### ISSUE TITLE
[client] createObjectURL vs FileReader 비교

### ISSUE THREAD

**Issue by saseungg** [saseungg/second-hand#12]
## ☑️ 진행할 작업
createObjectURL과 FileReader를 둘 다 적용해보고 성능을 비교해본다.

## 📝TODO
- [ ] FileReader 방식으로 적용해보기
- [ ] createObjectURL에 revoke 적용해서 메모리 해제
- [ ] 둘의 장단점을 도출해서 결론 내리기

## ⚙️기타
createObject가 성능면에서 더 좋다고는 하는데 직접 비교해보고 체감하기 위해 FileReader 버전으로도 구현해보기로했다.
