### ISSUE TITLE
[server] express 서버 초기 설정

### ISSUE THREAD

**Issue by saseungg** [saseungg/second-hand#19]
## ☑️ 진행할 작업
express 통한 서버 구축

## 📝TODO
- [x] express, mongoDB 학습
- [x] mongodb와 mongoose 설치
- [x] mongodb 생성
- [x] api 명세서 작성
- [x] express 초기 설정

## ⚙️기타
초기 설정을 하고 api 추가로 올리자!
