### ISSUE TITLE
[client] sticky로 header와 footer 고정시키기

### ISSUE THREAD

**Issue by saseungg** [saseungg/second-hand#5]
## ☑️ 진행할 작업
- layout 페이지별이 아닌 전체 컴포넌트에 묶어주기
- sticky로 header와 footer 묶어주기

## 📝TODO
- [x] sticky로 header와 footer 묶어주기
- [x] 레이아웃 컴포넌트 전체 묶어주기 (feat app.ts)
- [x] top 버튼, 글 작성 버튼 위치값 고정 시키기
- [x] 백그라운드 배경 고정시키기

## 🧐 고민사항
- sticky를 사용해서 header와 footer를 고정하니 문제들이 발생했음.
- 스크롤을 빠르게 내렸을 떄 위치가 깜빡거림 (고정되는 위치가 스크롤에 따라 결정되기 떄문에)
- fixed로도 처리가 가능한데 다양한 에러들을 해결하면서까지 sticky를 고집해야할 이유가 없어 fixed를 사용하기로 결정
