### ISSUE TITLE
[client] sticky가 아닌 fixed로 header, footer 고정시키기 (내부 스크롤 없애기)

### ISSUE THREAD

**Issue by saseungg** [saseungg/second-hand#6]
## ☑️ 진행할 작업
- sticky를 사용하면서 생기는 문제들(깨짐 현상, 위치값 고정시키기에 한계가 있음) fixed를 사용하기로 결정
  - #5 
- 대신 내부 스크롤을 제외시킬 거임 (원래 목적)

## 📝TODO
- [x] 내부 스크롤 제외시키기
- [x] fixed를 사용하여 header, footer 고정
- [x] 탑 버튼, 상품등록 버튼 고정시키기
- [x] 백그라운드 고정시키기
- [x] 카테고리에 스크롤 적용
- [x] 미디어쿼리가 1024px 이하로 줄어들었을때 높이값이 줄어드는 문제 해결

## ⚙️ 이후 할 작업들
- 스크롤 있는 페이지와 없는 페이지 밀리는 현상 해결하기
- 내부 스크롤 삭제로 탑버튼 스크롤 먹히지 않는 문제 해결하기
- 커스텀 훅 분리
