### ISSUE TITLE
[client] top 스크롤 커스텀 훅 분리 및 페이지별 스크롤 유무에 따른 위치 흔들림 해결하기

### ISSUE THREAD

**Issue by saseungg** [saseungg/second-hand#9]
## ☑️ 진행할 작업
- top 스크롤 커스텀 훅 분리
- 페이지별 스크롤 유무에 따른 위치 흔들림 해결하기

## 📝TODO
- [ ] 스크롤 내렸을 때 topbutton 등장하도록 하기
- [ ] 커스텀 훅 분리
- [ ] 스크롤 유무에 따른 위치 흔들림 해결
- [ ] fetch시 로딩 페이지 위로 올라가는 문제 해결
